// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: streaming-demo.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type ClientWritableStream,
  type handleBidiStreamingCall,
  type handleClientStreamingCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "streaming.demo";

export interface EchoRequest {
  message: string;
}

export interface EchoReply {
  message: string;
}

export interface SumRequest {
  value: number;
}

export interface SumReply {
  total: number;
}

export interface CountdownRequest {
  from: number;
}

export interface CountdownReply {
  value: number;
}

export interface ChatMessage {
  message: string;
}

function createBaseEchoRequest(): EchoRequest {
  return { message: "" };
}

export const EchoRequest: MessageFns<EchoRequest> = {
  encode(message: EchoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EchoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEchoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EchoRequest {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: EchoRequest): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EchoRequest>, I>>(base?: I): EchoRequest {
    return EchoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EchoRequest>, I>>(object: I): EchoRequest {
    const message = createBaseEchoRequest();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseEchoReply(): EchoReply {
  return { message: "" };
}

export const EchoReply: MessageFns<EchoReply> = {
  encode(message: EchoReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EchoReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEchoReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EchoReply {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: EchoReply): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EchoReply>, I>>(base?: I): EchoReply {
    return EchoReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EchoReply>, I>>(object: I): EchoReply {
    const message = createBaseEchoReply();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseSumRequest(): SumRequest {
  return { value: 0 };
}

export const SumRequest: MessageFns<SumRequest> = {
  encode(message: SumRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(8).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SumRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSumRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SumRequest {
    return { value: isSet(object.value) ? globalThis.Number(object.value) : 0 };
  },

  toJSON(message: SumRequest): unknown {
    const obj: any = {};
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SumRequest>, I>>(base?: I): SumRequest {
    return SumRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SumRequest>, I>>(object: I): SumRequest {
    const message = createBaseSumRequest();
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseSumReply(): SumReply {
  return { total: 0 };
}

export const SumReply: MessageFns<SumReply> = {
  encode(message: SumReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total !== 0) {
      writer.uint32(8).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SumReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSumReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SumReply {
    return { total: isSet(object.total) ? globalThis.Number(object.total) : 0 };
  },

  toJSON(message: SumReply): unknown {
    const obj: any = {};
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SumReply>, I>>(base?: I): SumReply {
    return SumReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SumReply>, I>>(object: I): SumReply {
    const message = createBaseSumReply();
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseCountdownRequest(): CountdownRequest {
  return { from: 0 };
}

export const CountdownRequest: MessageFns<CountdownRequest> = {
  encode(message: CountdownRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== 0) {
      writer.uint32(8).int32(message.from);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CountdownRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountdownRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.from = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CountdownRequest {
    return { from: isSet(object.from) ? globalThis.Number(object.from) : 0 };
  },

  toJSON(message: CountdownRequest): unknown {
    const obj: any = {};
    if (message.from !== 0) {
      obj.from = Math.round(message.from);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CountdownRequest>, I>>(base?: I): CountdownRequest {
    return CountdownRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CountdownRequest>, I>>(object: I): CountdownRequest {
    const message = createBaseCountdownRequest();
    message.from = object.from ?? 0;
    return message;
  },
};

function createBaseCountdownReply(): CountdownReply {
  return { value: 0 };
}

export const CountdownReply: MessageFns<CountdownReply> = {
  encode(message: CountdownReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(8).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CountdownReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountdownReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CountdownReply {
    return { value: isSet(object.value) ? globalThis.Number(object.value) : 0 };
  },

  toJSON(message: CountdownReply): unknown {
    const obj: any = {};
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CountdownReply>, I>>(base?: I): CountdownReply {
    return CountdownReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CountdownReply>, I>>(object: I): CountdownReply {
    const message = createBaseCountdownReply();
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseChatMessage(): ChatMessage {
  return { message: "" };
}

export const ChatMessage: MessageFns<ChatMessage> = {
  encode(message: ChatMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatMessage {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: ChatMessage): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatMessage>, I>>(base?: I): ChatMessage {
    return ChatMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessage>, I>>(object: I): ChatMessage {
    const message = createBaseChatMessage();
    message.message = object.message ?? "";
    return message;
  },
};

export type StreamingDemoService = typeof StreamingDemoService;
export const StreamingDemoService = {
  echo: {
    path: "/streaming.demo.StreamingDemo/Echo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EchoRequest): Buffer => Buffer.from(EchoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): EchoRequest => EchoRequest.decode(value),
    responseSerialize: (value: EchoReply): Buffer => Buffer.from(EchoReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): EchoReply => EchoReply.decode(value),
  },
  sum: {
    path: "/streaming.demo.StreamingDemo/Sum",
    requestStream: true,
    responseStream: false,
    requestSerialize: (value: SumRequest): Buffer => Buffer.from(SumRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SumRequest => SumRequest.decode(value),
    responseSerialize: (value: SumReply): Buffer => Buffer.from(SumReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): SumReply => SumReply.decode(value),
  },
  countdown: {
    path: "/streaming.demo.StreamingDemo/Countdown",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: CountdownRequest): Buffer => Buffer.from(CountdownRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CountdownRequest => CountdownRequest.decode(value),
    responseSerialize: (value: CountdownReply): Buffer => Buffer.from(CountdownReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): CountdownReply => CountdownReply.decode(value),
  },
  chat: {
    path: "/streaming.demo.StreamingDemo/Chat",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: ChatMessage): Buffer => Buffer.from(ChatMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer): ChatMessage => ChatMessage.decode(value),
    responseSerialize: (value: ChatMessage): Buffer => Buffer.from(ChatMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatMessage => ChatMessage.decode(value),
  },
} as const;

export interface StreamingDemoServer extends UntypedServiceImplementation {
  echo: handleUnaryCall<EchoRequest, EchoReply>;
  sum: handleClientStreamingCall<SumRequest, SumReply>;
  countdown: handleServerStreamingCall<CountdownRequest, CountdownReply>;
  chat: handleBidiStreamingCall<ChatMessage, ChatMessage>;
}

export interface StreamingDemoClient extends Client {
  echo(request: EchoRequest, callback: (error: ServiceError | null, response: EchoReply) => void): ClientUnaryCall;
  echo(
    request: EchoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: EchoReply) => void,
  ): ClientUnaryCall;
  echo(
    request: EchoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: EchoReply) => void,
  ): ClientUnaryCall;
  sum(callback: (error: ServiceError | null, response: SumReply) => void): ClientWritableStream<SumRequest>;
  sum(
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SumReply) => void,
  ): ClientWritableStream<SumRequest>;
  sum(
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SumReply) => void,
  ): ClientWritableStream<SumRequest>;
  sum(
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SumReply) => void,
  ): ClientWritableStream<SumRequest>;
  countdown(request: CountdownRequest, options?: Partial<CallOptions>): ClientReadableStream<CountdownReply>;
  countdown(
    request: CountdownRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<CountdownReply>;
  chat(): ClientDuplexStream<ChatMessage, ChatMessage>;
  chat(options: Partial<CallOptions>): ClientDuplexStream<ChatMessage, ChatMessage>;
  chat(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<ChatMessage, ChatMessage>;
}

export const StreamingDemoClient = makeGenericClientConstructor(
  StreamingDemoService,
  "streaming.demo.StreamingDemo",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): StreamingDemoClient;
  service: typeof StreamingDemoService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
